apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: wait-for-vpromq01
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup vpromq01; do echo "Waiting for RabbitMQ..."; sleep 2; done;']
      - name: wait-for-vprodb
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup vprodb; do echo "Waiting for MySQL..."; sleep 2; done;']
      containers:
      - name: app
        image: kubeanas/projectapp
        ports:
        - name: app-port
          containerPort: 8080