apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  selector:
    app: vprodb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: vprodb-port
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  selector:
    app: vprocache01
  ports:
  - protocol: TCP
    port: 11211
    targetPort: memcached-port
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  selector:
    app: vpromq01
  ports:
  - protocol: TCP
    port: 15672
    targetPort: rabbitmq-port
  type: ClusterIP