apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      nodeSelector:
        zone: us-east-1a
      initContainers:
      - name: init-busybox
        image: busybox:latest
        command: ["sh", "-c", "rm -rf /var/lib/mysql/lost+found"]
        volumeMounts:
        - name: vprodb
          mountPath: /var/lib/mysql
      containers:
      - name: vprodb
        image: kubeanas/projectdb
        ports:
        - name: vprodb-port
          containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: MYSQL_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: vprodb
          mountPath: /var/lib/mysql
      volumes:
      - name: vprodb
        awsElasticBlockStore:
          volumeID: vol-061d29d8578a7792f
          fsType: ext4