apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprocache01
  labels:
    app: vprocache01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprocache01
  template:
    metadata:
      labels:
        app: vprocache01
    spec:
      containers:
      - name: vprocache01
        image: memcached
        ports:
        - name: memcached-port
          containerPort: 11211

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  labels:
    app: vpromq01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpromq01
  template:
    metadata:
      labels:
        app: vpromq01
    spec:
      containers:
      - name: vpromq01
        image: rabbitmq
        ports:
        - name: rabbitmq-port
          containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: secret
              key: RABBITMQ_DEFAULT_PASS