apiVersion: v1
kind: Secret
metadata:
  name: secret
data:
  MYSQL_ROOT_PASSWORD: dnByb2RicGFzcw==  # Make sure this is the correct base64 encoded value
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=          # Make sure this is the correct base64 encoded value
type: Opaque